# Generated by Django 5.0.6 on 2024-12-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dw32qih2n/image/upload/v1733050419/user_default_jgcypw.png', null=True, upload_to='profiles/'),
        ),
    ]
