# Generated by Django 5.0.6 on 2024-10-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skils',
            new_name='Skills',
        ),
    ]
