# Generated by Django 5.0.6 on 2024-10-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_skils_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
