# Generated by Django 5.0.6 on 2024-11-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_social_github'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name']},
        ),
    ]
