# Generated by Django 5.0.6 on 2024-11-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_message_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
