# Generated by Django 5.0.6 on 2024-11-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_message_options_message_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
