# Generated by Django 5.0.6 on 2024-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dw32qih2n/image/upload/v1733065323/default_da6aid.jpg', null=True, upload_to=''),
        ),
    ]
